# CNB 云原生构建配置
# 参考文档: https://cnb.cool/docs

name: snake-game
version: 1.0.0
description: 头部动作控制的贪吃蛇游戏

# 构建环境
build:
  # 使用 Docker 镜像作为构建环境
  image: nginx:alpine
  # 构建命令
  commands:
    - echo "Building snake game..."
    - ls -la
    - cp index.html /usr/share/nginx/html/

# 部署配置
deploy:
  # 部署类型
  type: static
  # 静态文件目录
  static_dir: /usr/share/nginx/html
  # 端口配置
  port: 80

# 依赖配置
deps:
  - name: nginx
    version: latest

# 环境变量
env:
  - name: NODE_ENV
    value: production
