# CNB 云原生构建配置
# 参考文档: https://cnb.cool/docs

name: snake-game
version: 1.0.0
description: 头部动作控制的贪吃蛇游戏

# 构建配置
build:
  # 构建环境
  image: node:16-alpine
  # 构建命令
  script:
    - echo "Building snake game..."
    - ls -la
    - mkdir -p /app
    - cp index.html /app/

# 部署配置
deploy:
  # 部署类型
  type: static
  # 静态文件目录
  root: /app
  # 端口
  port: 80

# 环境变量
env:
  NODE_ENV: production
